import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  sidebar: [
    {
      type: "doc",
      id: "getstarted"
    },
    {
      type: "category",
      label: "CLI-Basic",
      items: [
      {
        type: 'doc',
        id: "cli"
      },{
        type: 'doc',
        id: "chat"
      },
      {
        type: 'doc',
        id: "server"
      },
    ]
    },
    //  {
    //   type: "category",
    //   label: "CLI-Advanced",
    //   items: [ {
    //     type: 'doc',
    //     id: "cli"
    //   },{
    //     type: 'doc',
    //     id: "chat"
    //   },]
    //   }
  ],
};

export default sidebars;
