import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  sidebar: [
    {
      type: "link",
      label: "Overview",
      href: "/",
    },
    "cli",
    // "server",
    // "capability",
    // "integration",
  ],
};

export default sidebars;
