name: Build and Test

on: 
  workflow_dispatch

jobs:
  macOS-arm64:
    runs-on: macos-14

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        id: cmake_build
        run: |
          cmake --preset arm64-apple-clang-release
          cmake --build build-arm64-apple-clang-release --config Release

  macOS-x64:
    runs-on: macos-13

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        id: cmake_build
        run: |
          cmake -B build
          cmake --build build

  Ubuntu:
    runs-on: ubuntu-22.04

    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        id: cmake_build
        run: |
          cmake -B build
          cmake --build build
  
  Windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Install Vulkan SDK
        run: |
          choco install vulkan-sdk -y

      - name: Remove local-only vcvars64.bat calls
        run: |
          (Get-Content build_vulkan.bat) -replace 'call\s+"?E:\\software_vs\\VC\\Auxiliary\\Build\\vcvars64\.bat"?', '' | Set-Content build_vulkan_ci.bat

      - name: Build with Vulkan
        run: |
          ./build_vulkan_ci.bat 
